// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBywJboiHJ47lmp9Pgtgm8K2JvATjNKOWE',
    appId: '1:271160084651:web:4071086e50288d650f4fee',
    messagingSenderId: '271160084651',
    projectId: 'rick-and-morty-char',
    authDomain: 'rick-and-morty-char.firebaseapp.com',
    storageBucket: 'rick-and-morty-char.firebasestorage.app',
    measurementId: 'G-KLC6LXPVG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxime99KKZurCL3vA54BcnrMPQ2zy1ey4',
    appId: '1:271160084651:android:1a81a0c3e47bf56e0f4fee',
    messagingSenderId: '271160084651',
    projectId: 'rick-and-morty-char',
    storageBucket: 'rick-and-morty-char.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lWlsBrPdwu90ouqkL_4u2fWIaf6nhbU',
    appId: '1:271160084651:ios:b7047515f43698020f4fee',
    messagingSenderId: '271160084651',
    projectId: 'rick-and-morty-char',
    storageBucket: 'rick-and-morty-char.firebasestorage.app',
    iosBundleId: 'com.example.rickAndMorty',
  );
}
